#!/usr/bin/env tsx
import { createInterface } from 'node:readline/promises';
import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readFile, rename, writeFile } from 'node:fs/promises';

type Answers = {
  databaseUrl: string;
  authEnabled: boolean;
  authToken: string;
  redisUrl: string;
  llmProvider: '' | 'openai' | 'anthropic';
  openaiApiKey: string;
  anthropicApiKey: string;
};

const DEFAULT_DATABASE_URL = 'postgresql://supermemory:supermemory_secret@localhost:15432/supermemory';
const DEFAULT_REDIS_URL = 'redis://localhost:16379';

function parseEnv(raw: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx <= 0) continue;
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1).trim();
    env[key] = value;
  }
  return env;
}

async function questionWithDefault(
  rl: ReturnType<typeof createInterface>,
  prompt: string,
  fallback: string
): Promise<string> {
  const answer = (await rl.question(`${prompt} [${fallback}]: `)).trim();
  return answer || fallback;
}

async function askYesNo(
  rl: ReturnType<typeof createInterface>,
  prompt: string,
  fallback: boolean
): Promise<boolean> {
  const label = fallback ? 'Y/n' : 'y/N';
  const answer = (await rl.question(`${prompt} (${label}): `)).trim().toLowerCase();
  if (!answer) return fallback;
  return answer === 'y' || answer === 'yes';
}

async function run(): Promise<void> {
  const existingEnv = existsSync('.env') ? parseEnv(await readFile('.env', 'utf-8')) : {};

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log('\nSupermemory setup configurator\n');
  console.log('Press Enter to accept defaults.\n');

  const useDefaultDb = await askYesNo(
    rl,
    'Use local Docker/Postgres default connection string?',
    true
  );
  const databaseUrl = useDefaultDb
    ? DEFAULT_DATABASE_URL
    : await questionWithDefault(
        rl,
        'DATABASE_URL',
        existingEnv.DATABASE_URL || DEFAULT_DATABASE_URL
      );

  const authEnabled = await askYesNo(
    rl,
    'Enable bearer-token auth for REST API?',
    (existingEnv.AUTH_ENABLED || 'false') === 'true'
  );
  const authToken = authEnabled
    ? await questionWithDefault(
        rl,
        'AUTH_TOKEN',
        existingEnv.AUTH_TOKEN || randomBytes(24).toString('base64url')
      )
    : '';

  const useRedis = await askYesNo(
    rl,
    'Use Redis queue workers (recommended for async extraction)?',
    true
  );
  const redisUrl = useRedis
    ? await questionWithDefault(rl, 'REDIS_URL', existingEnv.REDIS_URL || DEFAULT_REDIS_URL)
    : '';

  const llmChoice = await questionWithDefault(
    rl,
    'LLM provider (none/openai/anthropic)',
    existingEnv.LLM_PROVIDER || 'none'
  );
  const llmProvider: '' | 'openai' | 'anthropic' =
    llmChoice === 'openai' || llmChoice === 'anthropic' ? llmChoice : '';

  const openaiApiKey =
    llmProvider === 'openai'
      ? await questionWithDefault(rl, 'OPENAI_API_KEY', existingEnv.OPENAI_API_KEY || '')
      : existingEnv.OPENAI_API_KEY || '';
  const anthropicApiKey =
    llmProvider === 'anthropic'
      ? await questionWithDefault(rl, 'ANTHROPIC_API_KEY', existingEnv.ANTHROPIC_API_KEY || '')
      : existingEnv.ANTHROPIC_API_KEY || '';

  rl.close();

  const answers: Answers = {
    databaseUrl,
    authEnabled,
    authToken,
    redisUrl,
    llmProvider,
    openaiApiKey,
    anthropicApiKey,
  };

  if (existsSync('.env')) {
    const backupPath = `.env.backup-${Date.now()}`;
    await rename('.env', backupPath);
    console.log(`Backed up existing .env to ${backupPath}`);
  }

  const envText = `# Generated by scripts/setup.ts
DATABASE_URL=${answers.databaseUrl}
API_HOST=localhost
API_PORT=13000
API_HOST_PORT=13000

# Optional REST API auth
AUTH_ENABLED=${answers.authEnabled ? 'true' : 'false'}
AUTH_TOKEN=${answers.authToken}

# Optional queue workers (if unset, API falls back to inline processing)
REDIS_URL=${answers.redisUrl}
POSTGRES_HOST_PORT=15432
REDIS_HOST_PORT=16379
BULLMQ_CONCURRENCY_EXTRACTION=5
BULLMQ_CONCURRENCY_CHUNKING=3
BULLMQ_CONCURRENCY_EMBEDDING=2
BULLMQ_CONCURRENCY_INDEXING=1

# Optional LLM extraction provider
LLM_PROVIDER=${answers.llmProvider}
OPENAI_API_KEY=${answers.openaiApiKey}
ANTHROPIC_API_KEY=${answers.anthropicApiKey}

LLM_MODEL=
LLM_MAX_TOKENS=2000
LLM_TEMPERATURE=0.1
LLM_TIMEOUT_MS=30000
LLM_MAX_RETRIES=3
LLM_CACHE_ENABLED=true
LLM_CACHE_TTL_MS=900000

EMBEDDING_MODEL=text-embedding-3-small
EMBEDDING_DIMENSIONS=1536
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW_MS=60000
LOG_LEVEL=info
`;

  await writeFile('.env', envText, 'utf-8');

  console.log('\nWrote .env successfully.\n');
  console.log('Next steps:');
  console.log('1) Start dependencies: docker compose up -d postgres redis');
  console.log('2) Run migrations: ./scripts/migrations/run_migrations.sh');
  console.log('3) Validate config: npm run doctor');
  console.log('4) Start API: npm run dev');
}

run().catch((error) => {
  console.error('Setup failed:', error);
  process.exit(1);
});
